// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatLng } from "./LatLng";

export type AddressDto = { id: string, label: string, line1: string, line2: string | null, landmark: string | null, city: string, pincode: string, location: LatLng, 
/**
 * Store delivering to this address right now, if any.
 */
servingStoreId: string | null, };
