// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminProduct = { id: string, categoryId: string, categoryName: string, name: string, slug: string, brand: string | null, description: string | null, unitLabel: string, barcode: string | null, mrpPaise: number, pricePaise: number, imageUrls: Array<string>, isActive: boolean, createdAt: string, updatedAt: string, };
