// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/admin/orders/{id}/cancel` (support, store managers, admins).
 */
export type AdminCancelRequest = { reason: string, };
