// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminCategory = { id: string, parentId: string | null, name: string, slug: string, imageUrl: string | null, sortOrder: number, isActive: boolean, productCount: number, };
