// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoJsonPolygon } from "./GeoJsonPolygon";
import type { LatLng } from "./LatLng";

export type AdminStore = {
  id: string;
  code: string;
  name: string;
  address: string;
  location: LatLng;
  serviceArea: GeoJsonPolygon;
  /**
   * Square kilometres covered by `service_area`.
   */
  areaSqKm: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};
