// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type AdminUser = {
  id: string;
  phone: string;
  name: string | null;
  role: Role;
  storeId: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};
