// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VehicleType } from "./VehicleType";

/**
 * Shown to the customer once a rider is assigned.
 */
export type AssignedRider = {
  name: string | null;
  phone: string;
  vehicleType: VehicleType;
  vehicleNumber: string | null;
};
