// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BillSummary = {
  itemTotalPaise: number;
  mrpTotalPaise: number;
  deliveryFeePaise: number;
  totalPaise: number;
  /**
   * Orders at or above this item total ship free.
   */
  freeDeliveryAbovePaise: number;
};
