// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderStatus } from "./OrderStatus";
import type { PaymentMethod } from "./PaymentMethod";

/**
 * One card on the admin live board.
 */
export type BoardOrder = { id: string, number: string, status: OrderStatus, storeCode: string, paymentMethod: PaymentMethod, totalPaise: number, itemCount: number, riderPhone: string | null, createdAt: string, updatedAt: string, };
