// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillSummary } from "./BillSummary";
import type { CartLine } from "./CartLine";

export type CartResponse = { storeId: string, items: Array<CartLine>, itemCount: number, 
/**
 * Bill for the available lines only.
 */
bill: BillSummary, 
/**
 * True when every line can be ordered as is.
 */
canCheckout: boolean, };
