// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CartLine = { productId: string, name: string, brand: string | null, unitLabel: string, imageUrl: string | null, quantity: number, unitPricePaise: number, unitMrpPaise: number, lineTotalPaise: number, 
/**
 * False when the store stopped selling it or it's out of stock.
 */
available: boolean, maxQuantity: number, };
