// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogProduct = { id: string, categoryId: string, name: string, brand: string | null, unitLabel: string, imageUrls: Array<string>, mrpPaise: number, 
/**
 * What the customer pays at this store (store override or base price).
 */
pricePaise: number, inStock: boolean, 
/**
 * Cap for the quantity stepper: min(stock, per-item limit).
 */
maxQuantity: number, 
/**
 * Only on the product detail endpoint.
 */
description?: string, };
