// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/admin/categories`, `PUT /v1/admin/categories/{id}`.
 */
export type CategoryRequest = { name: string, 
/**
 * Derived from `name` when omitted.
 */
slug?: string, parentId?: string, imageUrl?: string, sortOrder: number, isActive: boolean, };
