// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentMethod } from "./PaymentMethod";

export type CheckoutRequest = {
  storeId: string;
  addressId: string;
  paymentMethod: PaymentMethod;
};
