// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderDetail } from "./OrderDetail";
import type { RazorpayCheckout } from "./RazorpayCheckout";

export type CheckoutResponse = { order: OrderDetail, 
/**
 * Present for `ONLINE`: open the Razorpay checkout with it.
 */
razorpay: RazorpayCheckout | null, };
