// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatLng } from "./LatLng";

export type DeliveryOffer = {
  orderId: string;
  number: string;
  storeName: string;
  storeAddress: string;
  storeLocation: LatLng;
  /**
   * Drop area only (full address after accepting).
   */
  dropArea: string;
  dropLocation: LatLng;
  /**
   * Rider -> store, metres (from the rider's last fix).
   */
  toStoreM: number | null;
  /**
   * Store -> customer, metres (straight line).
   */
  tripM: number;
  itemCount: number;
  bagCount: number | null;
  /**
   * Cash to collect at the door (0 if prepaid).
   */
  collectPaise: number;
  expiresAt: string;
};
