// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeliverRequest = { otp: string, 
/**
 * For cash on delivery: amount taken from the customer.
 */
codCollectedPaise?: number, };
