// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolygonType } from "./PolygonType";

/**
 * A GeoJSON Polygon: one outer ring of `[lng, lat]` positions (no holes).
 */
export type GeoJsonPolygon = { type: PolygonType, coordinates: Array<Array<[number, number]>>, };
