// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentStatus } from "./ComponentStatus";

export type HealthResponse = {
  status: ComponentStatus;
  database: ComponentStatus;
  redis: ComponentStatus;
  version: string;
};
