// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InventoryListQuery = { q?: string, 
/**
 * `true`: only products this store carries. `false`: only ones it doesn't.
 */
stocked?: boolean, };
