// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /v1/admin/stores/{storeId}/inventory/{productId}` (upsert).
 */
export type InventoryRequest = { quantity: number, 
/**
 * Shelf address, e.g. "A-03-2".
 */
binLocation?: string, 
/**
 * Store-specific price; omit to use the product's base price.
 */
priceOverridePaise?: number, isAvailable: boolean, };
