// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationPoint } from "./LocationPoint";

/**
 * Background location uploads come in batches; the newest point wins.
 */
export type LocationBatch = { points: Array<LocationPoint> };
