// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocationPoint = { lat: number, lng: number, accuracyM?: number, 
/**
 * Unix milliseconds when the device took the fix.
 */
recordedAt: number, };
