// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * The signed-in user, as returned by `/v1/auth/sync` and `/v1/auth/me`.
 */
export type MeResponse = {
  id: string;
  phone: string;
  name: string | null;
  role: Role;
  storeId: string | null;
  createdAt: string;
};
