// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metrics = { ordersToday: number, deliveredToday: number, cancelledToday: number, 
/**
 * Delivered order value today.
 */
gmvTodayPaise: number, 
/**
 * Order placed -> delivered, averaged over today's deliveries.
 */
avgDeliveryMinutes: number | null, ridersOnline: number, };
