// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemDto = { productId: string, name: string, brand: string | null, unitLabel: string, imageUrl: string | null, quantity: number, unitPricePaise: number, unitMrpPaise: number, pickedQuantity: number | null, };
