// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderStatus } from "./OrderStatus";

/**
 * Pushed on the `orders:{id}` and `stores:{storeId}:orders` Redis channels.
 */
export type OrderStatusChanged = {
  orderId: string;
  storeId: string;
  number: string;
  from: OrderStatus | null;
  status: OrderStatus;
  at: string;
};
