// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderStatus } from "./OrderStatus";

export type OrderEvent = {
  status: OrderStatus;
  note: string | null;
  at: string;
};
