// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderStatus =
  | "PLACED"
  | "CONFIRMED"
  | "PICKING"
  | "PACKED"
  | "RIDER_ASSIGNED"
  | "PICKED_UP"
  | "OUT_FOR_DELIVERY"
  | "DELIVERED"
  | "CANCELLED"
  | "PARTIALLY_FULFILLED";
