// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressSnapshot } from "./AddressSnapshot";
import type { BillSummary } from "./BillSummary";
import type { OrderEvent } from "./OrderEvent";
import type { OrderItemDto } from "./OrderItemDto";
import type { OrderStatus } from "./OrderStatus";
import type { PaymentMethod } from "./PaymentMethod";
import type { PaymentStatus } from "./PaymentStatus";

export type OrderDetail = {
  storeId: string;
  items: Array<OrderItemDto>;
  bill: BillSummary;
  address: AddressSnapshot;
  /**
   * Give this to the rider at the door. Hidden once the order is closed.
   */
  deliveryOtp: string | null;
  cancelReason: string | null;
  canCancel: boolean;
  events: Array<OrderEvent>;
  id: string;
  /**
   * Display number, e.g. `VG100001`.
   */
  number: string;
  status: OrderStatus;
  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  totalPaise: number;
  itemCount: number;
  createdAt: string;
};
