// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackRequest = { bagCount: number, 
/**
 * Where the bags wait for the rider, e.g. "S-03".
 */
stagingSlot?: string, };
