// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One page of a list endpoint.
 */
export type Page<T> = {
  items: Array<T>;
  total: number;
  limit: number;
  offset: number;
};
