// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/customer/orders/{id}/payment`: Razorpay checkout's success payload.
 */
export type PaymentVerifyRequest = { razorpayOrderId: string, razorpayPaymentId: string, razorpaySignature: string, };
