// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PickupRequest = {
  /**
   * Bags the rider collected; must match what the picker packed.
   */
  bagCount: number;
};
