// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PickLine = { productId: string, name: string, brand: string | null, unitLabel: string, imageUrl: string | null, barcode: string | null, 
/**
 * Shelf address, e.g. "A-03-2"; the list is sorted by it.
 */
binLocation: string | null, quantity: number, 
/**
 * None until counted; less than `quantity` means units are missing.
 */
pickedQuantity: number | null, };
