// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pushed on `orders:{id}` (as `riderLocation`) while the order is on its way.
 */
export type RiderLocation = {
  orderId: string;
  lat: number;
  lng: number;
  at: string;
};
