// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VehicleType } from "./VehicleType";

export type RiderMe = { isOnline: boolean, vehicleType: VehicleType, vehicleNumber: string | null, storeId: string | null, storeName: string | null, 
/**
 * The order the rider is currently delivering, if any.
 */
activeOrderId: string | null, deliveredToday: number, };
