// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pushed on `orders:{id}:rider` while the order is on its way (phase 7 map).
 */
export type RiderLocation = {
  orderId: string;
  lat: number;
  lng: number;
  at: string;
};
