// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VehicleType } from "./VehicleType";

export type RiderProfileRequest = {
  vehicleType: VehicleType;
  vehicleNumber?: string;
};
