// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Account role. Stored in Postgres (`user_role` enum), never taken from the token.
 */
export type Role = "CUSTOMER" | "PICKER" | "RIDER" | "ADMIN";
