// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PickLine } from "./PickLine";
import type { PickList } from "./PickList";

export type ScanResult = { 
/**
 * The line the scan counted towards.
 */
line: PickLine, 
/**
 * True when this scan completed the line.
 */
lineComplete: boolean, pickList: PickList, };
