// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoreSummary } from "./StoreSummary";

export type ServiceabilityResponse = {
  serviceable: boolean;
  store: StoreSummary | null;
};
