// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /v1/customer/cart/items/{productId}`; quantity 0 removes the line.
 */
export type SetCartItemRequest = { storeId: string; quantity: number };
