// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Manually set a line's count: for unlabelled items, or to mark units missing.
 */
export type SetPickedRequest = { pickedQuantity: number };
