// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoreSummary = { id: string, code: string, name: string, 
/**
 * Rough delivery estimate from store distance.
 */
etaMinutes: number, };
