// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoJsonPolygon } from "./GeoJsonPolygon";
import type { LatLng } from "./LatLng";

/**
 * `POST /v1/admin/stores`, `PUT /v1/admin/stores/{id}` (full replace).
 */
export type StoreRequest = { 
/**
 * e.g. `BLR-IND-01`
 */
code: string, name: string, address: string, location: LatLng, serviceArea: GeoJsonPolygon, isActive: boolean, };
