// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /v1/admin/stores/{id}/active`: switch a store on or off (store managers' own store).
 */
export type StoreActiveRequest = { isActive: boolean, };
