// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * `PATCH /v1/admin/users/{id}/role`
 */
export type UpdateRoleRequest = { role: Role; storeId?: string };
