// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UploadResponse = {
  /**
   * Relative (`/media/...`) for local storage; resolve against the API origin.
   */
  url: string;
};
