// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * `GET /v1/admin/users` filters (plus `limit`/`offset`).
 */
export type UserListQuery = { 
/**
 * Substring of the phone number, e.g. `98765`.
 */
phone?: string, role?: Role, };
