// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client -> server. The first message must be `auth`.
 */
export type WsClientMessage = { "type": "auth"; token: string };
