// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderStatusChanged } from "./OrderStatusChanged";

/**
 * Server -> client.
 */
export type WsServerMessage =
  | { "type": "ready" }
  | { "type": "order"; event: OrderStatusChanged }
  | { "type": "resync" }
  | { "type": "error"; code: string; message: string };
