// Regenerates src/index.ts as a barrel over the ts-rs output in src/bindings/.
// With --clean, empties src/bindings/ first so removed DTOs don't linger.
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const srcDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src");

if (process.argv.includes("--clean")) {
  rmSync(join(srcDir, "bindings"), { recursive: true, force: true });
  mkdirSync(join(srcDir, "bindings"));
  process.exit(0);
}
const names = readdirSync(join(srcDir, "bindings"))
  .filter((f) => f.endsWith(".ts"))
  .map((f) => f.slice(0, -3))
  .sort();

const body = names.map((n) => `export type { ${n} } from "./bindings/${n}";`).join("\n");
writeFileSync(
  join(srcDir, "index.ts"),
  `// Generated by scripts/gen-index.mjs from ts-rs bindings. Do not edit.\n${body}\n`,
);
console.log(`@vigo/types: indexed ${names.length} bindings`);
